project:
  type: website

website:
  title: "Test Quarto Pixi CI w/ Envs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: true  # never re-render during project render

