# Use a base image with Python pre-installed
FROM mcr.microsoft.com/devcontainers/python:3

# Set the home directory where Pixi will be installed
# ENV PIXI_HOME=/usr/local

# Install Pixi and other dependencies
# RUN curl -fsSL https://pixi.sh/install.sh | bash

# Add Pixi to PATH
# ENV PATH="/root/.pixi/bin:$PATH"


