services:
  tutorial-2-service:
    # image: mcr.microsoft.com/devcontainers/python:1-3.12-bookworm
    build: .devcontainer/tutorial_2_container/
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: sleep infinity
